---
title: ""
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---

```{r setup, include=FALSE}
library(flexdashboard)
library(tidyverse)
library(p8105.datasets)
library(plotly)

data("instacart")

getmode <- function(v) {
   uniqv <- unique(v)
   uniqv[which.max(tabulate(match(v, uniqv)))]
}
```

Column {data-width=650}
-----------------------------------------------------------------------

### Customers

```{r}
instacart %>%
  group_by(user_id, department) %>% 
  filter(department %in% c("alcohol", "personal care", "breakfast")) %>% 
  summarise(
    avg_days_between_order = mean(days_since_prior_order), 
    avg_items = mean(add_to_cart_order), 
    num_orders = max(order_number),
    fav_item = getmode(product_name)
  ) %>% 
  mutate(text_label = str_c("User ID: ", user_id, '\nDepartment: ', department, "\nAvg Days Between Orders: ", avg_days_between_order, "\nFavorite Product: ", fav_item)) %>%
  plot_ly(
    x = ~num_orders, y = ~avg_items, type = "scatter", mode = "markers",
    color = ~department, text = ~text_label, alpha = 0.5) %>% 
  layout(xaxis = list(title = "number of orders"), yaxis = list(title = "average items ordered"))
```

Column {data-width=350}
-----------------------------------------------------------------------

### Order of Item Added to Cart

```{r}
instacart %>% 
  filter(department %in% c("alcohol",  "breakfast", "personal care")) %>%
  plot_ly(y = ~add_to_cart_order, color = ~department, type = "box") %>% 
  layout(yaxis = list(title = "order added to cart"))
```

### Sales across the Week by Department

```{r}
instacart %>% filter(department %in% c("alcohol",  "breakfast", "personal care")) %>%
  group_by(department, order_dow) %>% 
  count() %>% 
  ungroup() %>% 
  group_by(department) %>% 
  mutate(prop = n / sum(n)) %>%
  mutate(
    order_dow = fct_relevel(factor(order_dow), c("0", "1", "2", "3", "4", "5", "6")),
    order_dow = recode(order_dow, '0' = "Monday", '1' = "Tuesday", '2'="Wednesday",      '3'="Thursday", '4'="Friday", '5'="Saturday", '6'="Sunday"), 
  ) %>% 
  ungroup() %>% 
  plot_ly(
    x = ~order_dow, y = ~prop, type = 'scatter', mode = 'lines',
    color = ~department) %>% 
  layout(xaxis = list(title = ""), yaxis = list(title = "proportion of orders"))
```

