---
title: "Dashboard"
output: 
  html_document
---

```{r}
data("instacart")
```

```{r}
table(instacart$department)
```



```{r}
instacart %>% 
  filter(department %in% c("alcohol",  "breakfast", "personal care")) %>%
  group_by(department, order_dow) %>% 
  count() %>% 
  ungroup() %>% 
  group_by(department) %>% 
  mutate(prop = n / sum(n)) %>%
  mutate(
    order_dow = fct_relevel(factor(order_dow), c("0", "1", "2", "3", "4", "5", "6")),
    order_dow = recode(order_dow, '0' = "Monday", '1' = "Tuesday", '2'="Wednesday",      '3'="Thursday", '4'="Friday", '5'="Saturday", '6'="Sunday"), 
  ) %>% 
  ungroup() %>% 
  ggplot(aes(x = order_dow, y = prop, group = department, color = department)) + 
  geom_point() + 
  geom_line() +
  labs(title = "Sales across the Week by Department", y = "proportion of orders in department", x = "day of week") + 
  viridis::scale_color_viridis(
    name = "Department", 
    discrete = TRUE
  ) + 
  theme_bw()
```


```{r}
instacart %>% 
  filter(department %in% c("alcohol",  "breakfast", "personal care")) %>%
  #group_by(department) %>% 
  #summarise(avg = mean (add_to_cart_order)) %>% 
  #mutate(department = fct_reorder(factor(department), avg)) %>% 
  ggplot(aes(x = department, y = add_to_cart_order, fill = department)) +
  geom_boxplot(show.legend = FALSE) + 
  coord_flip() + 
  labs(title = "Order of Item Added to Cart", y = "department", x = "order added to cart") + 
  viridis::scale_fill_viridis(
    name = "", 
    discrete = TRUE
  ) + 
  theme_bw()
  
```
```{r}
instacart %>% 
  filter(department %in% c("alcohol",  "breakfast", "personal care")) %>%
  plot_ly(y = ~add_to_cart_order, color = ~department, type = "box")
```


```{r}
instacart %>% 
  filter(reordered == 1) %>% 
  group_by(department) %>% 
  summarise(avg_days = mean(days_since_prior_order)) %>% 
  mutate(department = fct_reorder(factor(department), avg_days)) %>% 
  ggplot(aes(x = department, y = avg_days)) + 
  geom_bar(stat = "identity") + 
  coord_flip()
```

```{r}
instacart %>% 
  group_by(user_id, department) %>% 
  filter(department %in% c("alcohol", "personal care", "breakfast")) %>% 
  summarise(
    avg_days_between_order = mean(days_since_prior_order), 
    avg_items = mean(add_to_cart_order), 
    num_orders = max(order_number)
  ) %>% 
  #mutate(frequent_buyer = ifelse(avg_days_between_order < 10), TRUE) %>% 
  #filter(num_orders > 25, avg_items > 10 ) %>% 
  ggplot(aes(x = num_orders, y = avg_items, color = department)) + 
  geom_point(alpha = 0.5) +
  labs(title = "Instacart Alcohol, Breakfast, and Personal Care Consumers", y = "average items per order", x = "total number of orders") + 
  viridis::scale_color_viridis(
    name = "", 
    discrete = TRUE
  ) + 
  theme_bw()
```
```{r}
library(plotly)

instacart %>%
  group_by(user_id, department) %>% 
  filter(department %in% c("alcohol", "personal care", "breakfast")) %>% 
  summarise(
    avg_days_between_order = mean(days_since_prior_order), 
    avg_items = mean(add_to_cart_order), 
    num_orders = max(order_number)
  ) %>% 
  mutate(text_label = str_c("User ID: ", user_id, '\nDepartment: ', department, "\nAvg Days Between Orders: ", avg_days_between_order)) %>% 
  #rename("average items per order" = avg_items, "total number of orders" = num_orders) %>%  
  plot_ly(
    x = ~num_orders, y = ~avg_items, type = "scatter", mode = "markers",
    color = ~department, text = ~text_label, alpha = 0.5)
```


```{r}
instacart %>% 
  group_by(user_id, department) %>% 
  filter(department %in% c("alcohol", "personal care", "breakfast")) %>% 
  summarise(
    avg_days_between_order = mean(days_since_prior_order), 
    avg_items = mean(add_to_cart_order), 
    num_orders = max(order_number))
```

